---

- name: configure icinga2 ido feature
  template:
    src: etc/icinga2/features-available/ido-mysql.conf.j2
    dest: /etc/icinga2/features-available/ido-mysql.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  when: icinga2_master_ido_enabled|bool

- name: enable icinga2 ido feature
  file:
    src: /etc/icinga2/features-available/ido-mysql.conf
    dest: /etc/icinga2/features-enabled/ido-mysql.conf
    state: link
  when: icinga2_master_ido_enabled|bool

- name: install icinga2 configuration
  template:
    src: etc/icinga2/icinga2.conf.j2
    dest: /etc/icinga2/icinga2.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  notify: icinga2_master reload icinga2

- name: install icinga2 constants configuration
  template:
    src: etc/icinga2/constants.conf.j2
    dest: /etc/icinga2/constants.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  notify: icinga2_master reload icinga2

- name: remove files from conf.d which are already defined in global-templates
  copy:
    dest: '{{ item }}'
    content: ""
    force: yes
    mode: 0644
  loop:
    - /etc/icinga2/conf.d/services.conf
    - /etc/icinga2/conf.d/hosts.conf

# Twilio configuration
- name: install twilio sms scripts
  template:
    src: etc/icinga2/scripts/{{ item }}.j2
    dest: /etc/icinga2/scripts/{{ item }}
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: nagios_notification_plugin_exec_t
    selevel: s0
  loop:
    - twilio-sms-host-notification.sh
    - twilio-sms-service-notification.sh
  when: icinga2_master_twilio_sms_enabled|bool

- name: install twilio phone script
  template:
    src: etc/icinga2/scripts/{{ item }}.j2
    dest: /etc/icinga2/scripts/{{ item }}
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: nagios_notification_plugin_exec_t
    selevel: s0
  loop:
    - twilio-phone-notification.sh
  when: icinga2_master_twilio_phone_enabled|bool

- name: install icinga2 conf.d configurations
  template:
    src: etc/icinga2/conf.d/{{ item }}.j2
    dest: /etc/icinga2/conf.d/{{ item }}
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop:
    - "{{ icinga2_master_template_confd_apiusers }}"
    - "{{ icinga2_master_template_confd_notifications }}"
    - "{{ icinga2_master_template_confd_templates }}"
    - "{{ icinga2_master_template_confd_commands }}"
    - "{{ icinga2_master_template_confd_groups }}"
    - "{{ icinga2_master_template_confd_timeperiods }}"
    - "{{ icinga2_master_template_confd_users }}"
  notify: icinga2_master reload icinga2

- name: execute icinga2 api setup command
  command: icinga2 api setup
  args:
    creates: /var/lib/icinga2/ca/ca.crt
  notify: icinga2_master reload icinga2

- name: configure icinga2 api feature
  template:
    src: etc/icinga2/features-available/api.conf.j2
    dest: /etc/icinga2/features-available/api.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0

- name: enable icinga2 api feature
  file:
    src: /etc/icinga2/features-available/api.conf
    dest: /etc/icinga2/features-enabled/api.conf
    state: link

- name: configure icinga2 graphite feature
  template:
    src: etc/icinga2/features-available/graphite.conf.j2
    dest: /etc/icinga2/features-available/graphite.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  when: icinga2_master_graphite_enabled|bool
  notify: icinga2_master reload icinga2

- name: enable icinga2 graphite feature
  file:
    src: /etc/icinga2/features-available/graphite.conf
    dest: /etc/icinga2/features-enabled/graphite.conf
    state: link
  when: icinga2_master_graphite_enabled|bool
  notify: icinga2_master reload icinga2

# Global Icinga2 configuration
- name: ensure the global-templates directory is present
  file:
    dest: /etc/icinga2/zones.d/global-templates
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
    state: directory
  when: inventory_hostname == icinga2_client_monitoring_parents[0]

- name: create global template configurations
  template:
    src: etc/icinga2/zones.d/global-templates/{{ item }}.j2
    dest: /etc/icinga2/zones.d/global-templates/{{ item }}
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: "{{ icinga2_master_template_globaltemplates }}"
  notify: icinga2_master reload icinga2
  when: inventory_hostname == icinga2_client_monitoring_parents[0]

- name: create global zones configuration
  template:
    src: etc/icinga2/zones.conf.j2
    dest: /etc/icinga2/zones.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  notify: icinga2_master reload icinga2

- name: create zone configuration directory for each host
  file:
    path: /etc/icinga2/zones.d/{{ hostvars[item].inventory_hostname }}
    state: directory
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: '{{ groups["monitoring_sat"] }}'
  notify: icinga2_master reload icinga2
  when: >
      inventory_hostname == icinga2_client_monitoring_parents[0]
      and not ('icinga2_client_director_managed' in hostvars[item] and hostvars[item].icinga2_client_director_managed)

- name: create zone file for each zone
  template:
    src: etc/icinga2/zones.d/generic_zone.conf.j2
    dest: /etc/icinga2/zones.d/{{ hostvars[item].icinga2_master_client_parent_zone }}/{{ hostvars[item].inventory_hostname }}_zone.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: '{{ groups["monitoring_client"] }}'
  notify: icinga2_master reload icinga2
  when: >
      inventory_hostname == icinga2_client_monitoring_parents[0]
      and hostvars[item].inventory_hostname not in groups["monitoring_sat"]
      and not ('icinga2_client_director_managed' in hostvars[item] and hostvars[item].icinga2_client_director_managed)

- name: create host file per host
  template:
    src: etc/icinga2/zones.d/generic_host.conf.j2
    dest: /etc/icinga2/zones.d/{{ hostvars[item].icinga2_master_client_parent_zone }}/{{ hostvars[item].inventory_hostname }}_host.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: '{{ groups["monitoring_client"] }}'
  notify: icinga2_master reload icinga2
  when: >
      inventory_hostname == icinga2_client_monitoring_parents[0]
      and not ('icinga2_client_director_managed' in hostvars[item] and hostvars[item].icinga2_client_director_managed)

- name: add our own host configuration
  template:
    src: etc/icinga2/zones.d/generic_host.conf.j2
    dest: /etc/icinga2/zones.d/{{ hostvars[item].icinga2_master_client_parent_zone }}/{{ hostvars[item].inventory_hostname }}_host.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: '{{ groups["monitoring_master"] }}'
  notify: icinga2_master reload icinga2
  when: inventory_hostname == icinga2_client_monitoring_parents[0]
        and not ('icinga2_client_director_managed' in hostvars[item] and hostvars[item].icinga2_client_director_managed)

- name: ensure that icinga2 is started and enabled on boot
  service:
    name: icinga2
    state: started
    enabled: yes
