---
- name: configure icingadb feature
  template:
    src: etc/icinga2/features-available/icingadb.conf.j2
    dest: /etc/icinga2/features-available/icingadb.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  when: icinga2_master_icingadb_enabled|bool

- name: configure icingadb
  template:
    src: etc/icingadb/config.yml.j2
    dest: /etc/icingadb/config.yml
    owner: "icingadb"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  when: icinga2_master_icingadb_enabled|bool

- name: configure icingadb-redis
  template:
    src: etc/icingadb-redis/icingadb-redis.conf.j2
    dest: /etc/icingadb-redis/icingadb-redis.conf
    owner: "icingadb-redis"
    group: "{{ icinga2_master_group }}"
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  when: icinga2_master_icingadb_enabled|bool

- name: ensure that icingadb-redis is started and enabled on boot
  service:
    name: icingadb-redis
    state: restarted
    enabled: true
  when: icinga2_master_icingadb_enabled|bool

- name: ensure that icingadb is started and enabled on boot
  service:
    name: icingadb
    state: started
    enabled: true
  when: icinga2_master_icingadb_enabled|bool

- name: enable icingadb feature
  file:
    src: /etc/icinga2/features-available/icingadb.conf
    dest: /etc/icinga2/features-enabled/icingadb.conf
    state: link
  when: icinga2_master_icingadb_enabled|bool

- name: Configure icinga2 ido feature
  ansible.builtin.template:
    src: etc/icinga2/features-available/ido-mysql.conf.j2
    dest: /etc/icinga2/features-available/ido-mysql.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  when: icinga2_master_ido_enabled|bool

- name: Enable icinga2 ido feature
  ansible.builtin.file:
    src: /etc/icinga2/features-available/ido-mysql.conf
    dest: /etc/icinga2/features-enabled/ido-mysql.conf
    state: link
  when: icinga2_master_ido_enabled|bool

- name: Install icinga2 configuration
  ansible.builtin.template:
    src: etc/icinga2/icinga2.conf.j2
    dest: /etc/icinga2/icinga2.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  notify: Icinga2_master reload icinga2

- name: Install icinga2 constants configuration
  ansible.builtin.template:
    src: etc/icinga2/constants.conf.j2
    dest: /etc/icinga2/constants.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  notify: Icinga2_master reload icinga2

- name: Remove files from conf.d which are already defined in global-templates
  ansible.builtin.copy:
    dest: "{{ item }}"
    content: ""
    force: true
    mode: "0644"
  loop:
    - /etc/icinga2/conf.d/services.conf
    - /etc/icinga2/conf.d/hosts.conf

# Twilio configuration
- name: Install twilio sms scripts
  ansible.builtin.template:
    src: etc/icinga2/scripts/{{ item }}.j2
    dest: /etc/icinga2/scripts/{{ item }}
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0755"
    seuser: system_u
    serole: object_r
    setype: nagios_notification_plugin_exec_t
    selevel: s0
  loop:
    - twilio-sms-host-notification.sh
    - twilio-sms-service-notification.sh
  when: icinga2_master_twilio_sms_enabled|bool

- name: Install twilio phone script
  ansible.builtin.template:
    src: etc/icinga2/scripts/{{ item }}.j2
    dest: /etc/icinga2/scripts/{{ item }}
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0755"
    seuser: system_u
    serole: object_r
    setype: nagios_notification_plugin_exec_t
    selevel: s0
  loop:
    - twilio-phone-notification.sh
  when: icinga2_master_twilio_phone_enabled|bool

- name: Install icinga2 conf.d configurations
  ansible.builtin.template:
    src: etc/icinga2/conf.d/{{ item }}.j2
    dest: /etc/icinga2/conf.d/{{ item }}
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop:
    - "{{ icinga2_master_template_confd_apiusers }}"
    - "{{ icinga2_master_template_confd_notifications }}"
    - "{{ icinga2_master_template_confd_templates }}"
    - "{{ icinga2_master_template_confd_commands }}"
    - "{{ icinga2_master_template_confd_groups }}"
    - "{{ icinga2_master_template_confd_timeperiods }}"
    - "{{ icinga2_master_template_confd_users }}"
  notify: Icinga2_master reload icinga2

- name: Execute icinga2 api setup command
  ansible.builtin.command: icinga2 api setup
  args:
    creates: /var/lib/icinga2/ca/ca.crt
  notify: Icinga2_master reload icinga2

- name: Configure icinga2 api feature
  ansible.builtin.template:
    src: etc/icinga2/features-available/api.conf.j2
    dest: /etc/icinga2/features-available/api.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0

- name: Enable icinga2 api feature
  ansible.builtin.file:
    src: /etc/icinga2/features-available/api.conf
    dest: /etc/icinga2/features-enabled/api.conf
    state: link

- name: Configure icinga2 graphite feature
  ansible.builtin.template:
    src: etc/icinga2/features-available/graphite.conf.j2
    dest: /etc/icinga2/features-available/graphite.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  when: icinga2_master_graphite_enabled|bool
  notify: Icinga2_master reload icinga2

- name: Enable icinga2 graphite feature
  ansible.builtin.file:
    src: /etc/icinga2/features-available/graphite.conf
    dest: /etc/icinga2/features-enabled/graphite.conf
    state: link
  when: icinga2_master_graphite_enabled|bool
  notify: Icinga2_master reload icinga2

# Global Icinga2 configuration
- name: Ensure the global-templates directory is present
  ansible.builtin.file:
    dest: /etc/icinga2/zones.d/global-templates
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0755"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
    state: directory
  when: inventory_hostname == icinga2_client_monitoring_parents[0]

- name: Create global template configurations
  ansible.builtin.template:
    src: etc/icinga2/zones.d/global-templates/{{ item }}.j2
    dest: /etc/icinga2/zones.d/global-templates/{{ item }}
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: "{{ icinga2_master_template_globaltemplates }}"
  notify: Icinga2_master reload icinga2
  when: inventory_hostname == icinga2_client_monitoring_parents[0]

- name: Create global zones configuration
  ansible.builtin.template:
    src: etc/icinga2/zones.conf.j2
    dest: /etc/icinga2/zones.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  notify: Icinga2_master reload icinga2

- name: Create zone configuration directory for each host
  ansible.builtin.file:
    path: /etc/icinga2/zones.d/{{ hostvars[item].inventory_hostname }}
    state: directory
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0755"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: '{{ groups["monitoring_sat"] }}'
  notify: Icinga2_master reload icinga2
  when: >
    inventory_hostname == icinga2_client_monitoring_parents[0]
    and not ('icinga2_client_director_managed' in hostvars[item] and hostvars[item].icinga2_client_director_managed)

- name: Create zone file for each zone
  ansible.builtin.template:
    src: etc/icinga2/zones.d/generic_zone.conf.j2
    dest: /etc/icinga2/zones.d/{{ hostvars[item].icinga2_master_client_parent_zone }}/{{ hostvars[item].inventory_hostname }}_zone.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: '{{ groups["monitoring_client"] }}'
  notify: Icinga2_master reload icinga2
  when: >
    inventory_hostname == icinga2_client_monitoring_parents[0]
    and hostvars[item].inventory_hostname not in groups["monitoring_sat"]
    and not ('icinga2_client_director_managed' in hostvars[item] and hostvars[item].icinga2_client_director_managed)

- name: Create host file per host
  ansible.builtin.template:
    src: etc/icinga2/zones.d/generic_host.conf.j2
    dest: /etc/icinga2/zones.d/{{ hostvars[item].icinga2_master_client_parent_zone }}/{{ hostvars[item].inventory_hostname }}_host.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: '{{ groups["monitoring_client"] }}'
  notify: Icinga2_master reload icinga2
  when: >
    inventory_hostname == icinga2_client_monitoring_parents[0]
    and not ('icinga2_client_director_managed' in hostvars[item] and hostvars[item].icinga2_client_director_managed)

- name: Ensure master zone folder exists
  ansible.builtin.file:
    path: /etc/icinga2/zones.d/{{ hostvars[item].icinga2_master_client_parent_zone }}/
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
    state: directory
  loop: '{{ groups["monitoring_master"] }}'
  notify: Icinga2_master reload icinga2
  when: inventory_hostname == icinga2_client_monitoring_parents[0] and not ('icinga2_client_director_managed' in hostvars[item] and hostvars[item].icinga2_client_director_managed) # noqa: yaml[line-length]

- name: Add our own host configuration
  ansible.builtin.template:
    src: etc/icinga2/zones.d/generic_host.conf.j2
    dest: /etc/icinga2/zones.d/{{ hostvars[item].icinga2_master_client_parent_zone }}/{{ hostvars[item].inventory_hostname }}_host.conf
    owner: "{{ icinga2_master_owner }}"
    group: "{{ icinga2_master_group }}"
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: '{{ groups["monitoring_master"] }}'
  notify: Icinga2_master reload icinga2
  when: inventory_hostname == icinga2_client_monitoring_parents[0] and not ('icinga2_client_director_managed' in hostvars[item] and hostvars[item].icinga2_client_director_managed) # noqa: yaml[line-length]

- name: Ensure that icinga2 is started and enabled on boot
  ansible.builtin.service:
    name: icinga2
    state: started
    enabled: true
