---
- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - role::icinga2_master
    - role::icinga2_master:install
    - role::icinga2_master:config

- name: Import installation tasks
  ansible.builtin.import_tasks: installation.yml
  tags:
    - role::icinga2_master
    - role::icinga2_master:install

- name: Iport configuration tasks
  ansible.builtin.import_tasks: configuration.yml
  tags:
    - role::icinga2_master
    - role::icinga2_master:config
